### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by soundsnow** [JoppyFurr/Snepulator#4]
col|sms|gg|sg|sc|sf

**Comment by JoppyFurr** [comment]
I'm not sure how a list of extensions as an "issue", but will make a comment on each then close this.
Unless otherwise stated, I refer to the PC (Linux) version of Snepulator which this repository contains.

.col - ColecoVision emulation is supported on Snepulator, however it is still under development. Not all controller types or video modes have been implemented yet. ColecoVision support will not be added to an Android port of Snepulator until it is closer to complete.

.sms - Master System emulation is the primary target of Snepulator. Most games have been tested and should be working fine. The exceptions I'm aware of being games that require the Sports Pad, and one of the Korean games which changes the bit-order of data in the mapper to flip sprite directions.

.gg - Game Gear is supported by Snepulator. While I haven't tested every possible game, all that I have tested have run without issue.

.sg - SG-1000 is supported by Snepulator. To my knowledge the only SG-1000 game that is not supported is Terebi Oekaki, which requires support for the Sega Graphic Board.

.sc - SC-3000 is not yet supported by any version of Snepulator. There is additional development required for this to work (keyboard input device, tape drive support, etc. 

.sf - Super Control Station is not yet supported by any version of Snepulator. In addition to the SC-3000 requirements above, this also requiress emulation of the floppy drive.

For each of the unimplemented features mentioned above, these are things I would like to implement when I am able to find the time. However, as a hobby project and not my full time job, adding support for these features has no fixed timeline.
